name: Feature Request
description: Submit a feature request
labels: ["Enhancement"]
assignees:
  - TheClassic36
body:
  - type: textarea
    id: what-is-it
    attributes:
      label: What would you like to see added/changed?
      description: A clear and concise description of what you would like to see added or changed.
      placeholder: "Example: I would like a recipe that allows me to eat Grass Blocks. The recipe would be 4 Sugar surrounding a Grass Block."
    validations:
      required: true