modLoader="lowcodefml"
loaderVersion="[55,)"
license="MIT"

[[mods]]
modId="silly_eatables"
version="3.2.2"
displayName="Silly Eatables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/silly_eatables"
credits="https://github.com/Classic36-Media/Silly_Eatables/wiki/Credits"
authors="Classic36"
description="Eat things you shouldn't with these silly food recipes!"

[[dependencies.silly_eatables]]
    modId="forge"
    mandatory=true
    versionRange="[55,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.silly_eatables]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.21.8]"
    ordering="AFTER"
    side="BOTH"